# Generated by Django 6.0.3 on 2026-03-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='Mumbai', max_length=200),
        ),
    ]
